"""create syntage_webhook_events table

Revision ID: f6a1e9d58708
Revises: 
Create Date: 2026-04-28 12:14:09.824712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6a1e9d58708'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('syntage_webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('syntage_event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment="Ej: 'invoice.created'"),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('resource', sa.String(length=500), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Cuándo entró el webhook a nuestro endpoint'),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True, comment='Cuándo terminó el procesamiento (exitoso o fallido)'),
    sa.Column('syntage_timestamp', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('syntage_event_id')
    )
    op.create_index('ix_event_status_received', 'syntage_webhook_events', ['status', 'received_at'], unique=False)
    op.create_index('ix_event_type', 'syntage_webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_syntage_webhook_events_status'), 'syntage_webhook_events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_syntage_webhook_events_status'), table_name='syntage_webhook_events')
    op.drop_index('ix_event_type', table_name='syntage_webhook_events')
    op.drop_index('ix_event_status_received', table_name='syntage_webhook_events')
    op.drop_table('syntage_webhook_events')
    # ### end Alembic commands ###
